#!/bin/bash

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/repamotd"
CONFIG_FILE="${CONFIG_DIR}/env"
PLUGIN_DIR="${CONFIG_DIR}/plugins"

if [ -f $CONFIG_FILE ]; then
  source $CONFIG_FILE
fi

run-parts $PLUGIN_DIR
