#!/bin/bash

# set column width
COLUMNS=2

RST="\e[0m"
W=${COLOR_N:-"\e[0m"}
N=${COLOR_H1:-"\e[0;38;5;2m"}
G=${COLOR_H2:-"\e[1;38;5;10m"}
R=${COLOR_E2:-"\e[1;38;5;1m"}
M=${COLOR_T1:-"\e[1;38;5;15m"}
T=${COLOR_T2:-"\e[0m"}

mapfile -t containers < <(docker ps -a --format '{{.Names}}\t{{.Status}}' | sort -k1 | awk '{ print $1,$2 }')

out=""
for i in "${!containers[@]}"; do
    IFS=" " read name status <<< ${containers[i]}
    # color green if service is active, else red
    if [[ "${status}" == "Up" ]]; then
        out+="${T}${name}:,${G}${status,,}${RST},"
    else
        out+="${T}${name}:,${R}${status,,}${RST},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($i+1) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done

printf "\n${M}docker status:${RST}\n"
if [ -z "$out" ]; then
  echo -e "  ${T}no containers configured${RST}"
else
  printf "$out" | column -ts $',' | sed -e 's/^/  /'
  echo ""
fi
