#!/bin/bash

# config
max_usage=90
bar_width=40

RST="\033[0m"
W=${COLOR_N:-"\033[0m"}
N=${COLOR_H1:-"\033[0;38;5;2m"}
G=${COLOR_H2:-"\033[1;38;5;10m"}
R=${COLOR_E2:-"\033[0;38;5;1m"}
M=${COLOR_T1:-"\033[1;38;5;15m"}
T=${COLOR_T2:-"\033[0m"}
B=${COLOR_B:-"\033[0m"}

BAR_F="■" # "█"
BAR_E="□" # "░"

# disk usage: ignore zfs, squashfs & tmpfs
mapfile -t dfs < <(df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2)
printf "\n${M}disk usage:${W}\n"

for line in "${dfs[@]}"; do
    # get disk usage
    usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')
    used_width=$((($usage*$bar_width)/100))
    # color is green if usage < max_usage, else red
    if [ "${usage}" -ge "${max_usage}" ]; then
        color=$R
    else
        color=$G
    fi
    # print green/red bar until used_width
    bar="${color}"
    for ((i=0; i<$used_width; i++)); do
        bar+=$BAR_F
    done
    # print dimmmed bar until end
    bar+="$W"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+=$BAR_E
    done
    bar+="${W}"
    # print usage line & bar
    echo -e "${line}" | awk -v W=$W -v T=$T -v G=$G -v C=$color '{ printf(T "%-24s" C "%+3s" W " / " G "%+4s" W, $1, $2, $3); }' | sed -e 's/^/  /'
    echo -e "${bar}${RST}" | sed -e 's/^/  /'
done
